### ISSUE TITLE
inventory.py missing static methods

### ISSUE THREAD

**Issue by Raigeki-null** [Zephrym/TerminalPublic#1]
originally attempted to use
`GetEmptySlotCount(inventoryType)`
then found that there were quite a few missing static methods under inventory.

**Comment by Zephrym** [comment]
Thank you for the report. Will take a look at this tonight.

**Comment by Zephrym** [comment]
Looks like I used the outdated Doc when I made that class. Will fix this sometime today and push an update

**Comment by Zephrym** [comment]
Fixed
