### ISSUE TITLE
Terminal.LogOut()

### ISSUE THREAD

**Issue by Raigeki-null** [Zephrym/TerminalPublic#3]
Terminal module in the IDE labels logout function as Terminal.LogOut(), but terminal looks for Terminal.Logout().

**Comment by Zephrym** [comment]
Fixed in [commit: c61f8f4b2c26ba3efcec02b7267a98940a8982ab](https://github.com/Zephrym/TerminalPublic/tree/c61f8f4b2c26ba3efcec02b7267a98940a8982ab)
