### ISSUE TITLE
Removed Experimental Libs With Imports Still Expected

### ISSUE THREAD

**Issue by ColorlessBlood** [Zephrym/TerminalPublic#6]
Hiya,

Basically I've noticed you removed the experimental libs "player" and "npc."

But you still call to import them for out of game testing.

I did a clean install and it took me a bit to realize why I was getting errors.

https://i.imgur.com/Xt6drAo.png
https://i.imgur.com/dgSBBKN.png

I believe this is the problem, but I could be wrong.

**Comment by Zephrym** [comment]
Sorry about that. I will add the Npc class back in at a different date. I pushed a temp fix for now
in https://github.com/Zephrym/TerminalPublic/commit/361eb69ae8834916c123dd51fd93f04869f6246e
